# Generated by Django 5.0.1 on 2024-01-11 02:38

import ckeditor.fields
import core_app.models
import django.db.models.deletion
import shortuuid.django_fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cat', unique=True, verbose_name='カテゴリーのid')),
                ('title', models.CharField(default='Food', max_length=100, verbose_name='カテゴリー名')),
                ('image', models.ImageField(default='category.jpg', upload_to='category', verbose_name='カテゴリーの写真')),
            ],
            options={
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=99999999999999, verbose_name='金額')),
                ('paid_status', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='予約の日付')),
                ('package_status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=300, verbose_name='パッケージのステータス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name_plural': '予約',
            },
        ),
        migrations.CreateModel(
            name='BookPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_status', models.CharField(max_length=200, verbose_name='パッケージのステータス')),
                ('item', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200, verbose_name='写真')),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=99999999999999)),
                ('total', models.DecimalField(decimal_places=2, default='1.99', max_digits=99999999999999)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.book', verbose_name='予約')),
            ],
            options={
                'verbose_name_plural': 'パッケージの予約',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', unique=True, verbose_name='パッケージのid')),
                ('title', models.CharField(default='Fresh Pear', max_length=100, verbose_name='パッケージの名')),
                ('image', models.ImageField(default='product.jpg', upload_to=core_app.models.user_directory_path, verbose_name='パッケージの写真')),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=99999999999999, verbose_name='金額')),
                ('old_price', models.DecimalField(decimal_places=2, default="2.99,verbose_name='金額'", max_digits=99999999999999)),
                ('prefecture', models.CharField(choices=[('', '都道府県を選択してください'), ('Hokkaido', '北海道'), ('Aomori', '青森県'), ('Iwate', '岩手県'), ('Miyagi', '宮城県'), ('Akita', '秋田県'), ('Yamagata', '山形県'), ('Fukushima', '福島県'), ('Ibaraki', '茨城県'), ('Tochigi', '栃木県'), ('Gunma', '群馬県'), ('Saitama', '埼玉県'), ('Chiba', '千葉県'), ('Tokyo', '東京都'), ('Kanagawa', '神奈川県'), ('Niigata', '新潟県'), ('Toyama', '富山県'), ('Ishikawa', '石川県'), ('Fukui', '福井県'), ('Yamanashi', '山梨県'), ('Nagano', '長野県'), ('Gifu', '岐阜県'), ('Shizuoka', '静岡県'), ('Aichi', '愛知県'), ('Mie', '三重県'), ('Shiga', '滋賀県'), ('Kyoto', '京都府'), ('Osaka', '大阪府'), ('Hyogo', '兵庫県'), ('Nara', '奈良県'), ('Wakayama', '和歌山県'), ('Tottori', '鳥取県'), ('Shimane', '島根県'), ('Okayama', '岡山県'), ('Hiroshima', '広島県'), ('Yamaguchi', '山口県'), ('Tokushima', '徳島県'), ('Kagawa', '香川県'), ('Ehime', '愛媛県'), ('Kochi', '高知県'), ('Fukuoka', '福岡県'), ('Saga', '佐賀県'), ('Nagasaki', '長崎県'), ('Kumamoto', '熊本県'), ('Oita', '大分県'), ('Miyazaki', '宮崎県'), ('Kagoshima', '鹿児島県'), ('Okinawa', '沖縄県')], default='東京', max_length=200, verbose_name='都道府県')),
                ('location', models.CharField(max_length=200, verbose_name='場所')),
                ('package_status', models.CharField(choices=[('unpublished', 'unpublished'), ('published', 'Published')], default='unpublished', max_length=200, verbose_name='パッケージのステータス')),
                ('status', models.BooleanField(default=True, verbose_name='ステータス')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='アップデート日付')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='core_app.category', verbose_name='カテゴリー')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name_plural': 'パッケージ',
            },
        ),
        migrations.CreateModel(
            name='PackageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='package.jpg', upload_to='package-images', verbose_name='追加写真')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='core_app.package')),
            ],
            options={
                'verbose_name_plural': '追加写真',
            },
        ),
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='レヴュー')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core_app.package', verbose_name='パッケージ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name_plural': 'パッケージのレヴュー',
            },
        ),
    ]
