# Generated by Django 5.0.1 on 2024-01-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_section_package_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='title',
            new_name='name',
        ),
    ]
