# Generated by Django 5.0.1 on 2024-01-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_rename_title_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount',
            field=models.IntegerField(default=10),
        ),
    ]
