# Generated by Django 5.0.1 on 2024-01-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_package_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='old_price',
        ),
    ]
