# Generated by Django 5.0.1 on 2024-01-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_alter_package_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='discount',
        ),
    ]
