# Generated by Django 5.0.1 on 2024-01-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_remove_package_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpackage',
            name='package_status',
        ),
    ]
