# Generated by Django 5.0.1 on 2024-01-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_remove_bookpackage_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpackage',
            name='total',
        ),
    ]
