# Generated by Django 5.0.1 on 2024-01-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='package_status',
            field=models.CharField(choices=[('not visit', '旅行先に着てない'), ('visited', '旅行先に着いた'), ('visiting', '旅行中'), ('finished', '旅行完了')], default='processing', max_length=300, verbose_name='パッケージのステータス'),
        ),
    ]
