# Generated by Django 5.0.1 on 2024-01-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_alter_book_package_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': '住所'},
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='date',
            field=models.DateTimeField(verbose_name='日付'),
        ),
    ]
