# Generated by Django 5.0.1 on 2024-01-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_alter_address_options_alter_packagereview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予約の日付'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日付'),
        ),
    ]
