# Generated by Django 4.2.7 on 2024-02-07 02:08

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0017_outinactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='id')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='都道府県')),
            ],
            options={
                'verbose_name_plural': '都道府県',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='id')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='駐車場')),
            ],
            options={
                'verbose_name_plural': '駐車場',
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='id')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='お気に入りの旅行のアクティビティ何ですか？')),
            ],
            options={
                'verbose_name_plural': '旅行のアクティビティ',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='id')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='場所の中にあるもの')),
            ],
            options={
                'verbose_name_plural': '場所の中にあるもの',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='id')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='公共交通機関アクセス')),
            ],
            options={
                'verbose_name_plural': '公共交通機関アクセス',
            },
        ),
    ]
