# Generated by Django 4.2.7 on 2024-02-07 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0018_location_parking_personality_subcategory_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='location',
        ),
        migrations.RemoveField(
            model_name='package',
            name='prefecture',
        ),
        migrations.RemoveField(
            model_name='package',
            name='search',
        ),
        migrations.RemoveField(
            model_name='package',
            name='specification',
        ),
        migrations.AddField(
            model_name='package',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='core_app.outinactivity', verbose_name='インドアアウトドア❓'),
        ),
        migrations.AddField(
            model_name='package',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefecturee', to='core_app.location', verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='package',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking', to='core_app.parking', verbose_name='駐車場'),
        ),
        migrations.AddField(
            model_name='package',
            name='personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personality', to='core_app.personality', verbose_name='お気に入りの旅行のアクティビティ何ですか？❓'),
        ),
        migrations.AddField(
            model_name='package',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='core_app.subcategory', verbose_name='場所の中にあるもの'),
        ),
        migrations.AddField(
            model_name='package',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport', to='core_app.transport', verbose_name='公共交通機関アクセス'),
        ),
        migrations.AlterField(
            model_name='package',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.section', verbose_name='セクション'),
        ),
    ]
